services:
  nginx:
    volumes:
      - .:/var/www/html 

  app:
    build:
      context: .
      target: development
    image: app:dev
    volumes:
      - .:/var/www/html 
      - vendor_data:/var/www/html/vendor
      - node_modules_data:/var/www/html/node_modules
    environment:
      - APP_DEBUG=true

  phpmyadmin:
    image: phpmyadmin:5.2-apache
    container_name: ntbook_phpmyadmin 
    restart: unless-stopped 
    ports: 
      - "8081:80"
    environment: 
      - PMA_HOST=${PMA_HOST}
      - PMA_PORT=${PMA_PORT}
      - PMA_USER=${PMA_USER}
      - PMA_PASSWORD=${PMA_PASSWORD}
    depends_on: 
      mysql:
        condition: service_started 
    networks:
      - ntbook_network 

  node:
    image: node:22-alpine
    container_name: ntbook_node
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - node_modules_data:/var/www/html/node_modules
    command: sh -c "npm install && npm run dev"
    ports:
      - "5173:5173"   # Vite
    networks:
      - ntbook_network
  
volumes:
  vendor_data:
  node_modules_data:
